import type { Word } from './word.types';

export const words: Word[] = [
  // 음식
  { id: 'food-rice',        label: '밥',        categoryId: 'food', emoji: '🍚', image: '/aac/food/rice.png' },
  { id: 'food-noodle',      label: '라면',      categoryId: 'food', emoji: '🍜' },
  { id: 'food-bread',       label: '빵',        categoryId: 'food', emoji: '🍞', image: '/aac/food/bread.png' },
  { id: 'food-water',       label: '물',        categoryId: 'food', emoji: '💧', image: '/aac/food/water.png' },
  { id: 'food-milk',        label: '우유',      categoryId: 'food', emoji: '🥛', image: '/aac/food/milk.png' },
  { id: 'food-fruit',       label: '과일',      categoryId: 'food', emoji: '🍎', image: '/aac/food/fruit.png' },
  { id: 'food-snack',       label: '과자',      categoryId: 'food', emoji: '🍪', image: '/aac/food/snack.png' },
  { id: 'food-soup',        label: '국',        categoryId: 'food', emoji: '🍲' },
  { id: 'food-vegetable',   label: '채소',      categoryId: 'food', emoji: '🥦', image: '/aac/food/vegetable.png' },
  { id: 'food-cake',        label: '케이크',    categoryId: 'food', emoji: '🎂', image: '/aac/food/cake.png' },
  { id: 'food-juice',       label: '주스',      categoryId: 'food', emoji: '🥤', image: '/aac/food/juice.png' },
  { id: 'food-icecream',    label: '아이스크림', categoryId: 'food', emoji: '🍦', image: '/aac/food/icecream.png' },
  { id: 'food-candy',       label: '사탕',      categoryId: 'food', emoji: '🍬', image: '/aac/food/candy.png' },
  { id: 'food-egg',         label: '달걀',      categoryId: 'food', emoji: '🥚', image: '/aac/food/egg.png' },
  { id: 'food-meat',        label: '고기',      categoryId: 'food', emoji: '🥩', image: '/aac/food/meat.png' },
  { id: 'food-kimchi',      label: '김치',      categoryId: 'food', emoji: '🥬', image: '/aac/food/kimchi.png' },

  // 감정
  { id: 'emotion-happy',         label: '좋아',   categoryId: 'emotion', emoji: '😊', image: '/aac/emotion/happy.png' },
  { id: 'emotion-dislike',       label: '싫어',   categoryId: 'emotion', emoji: '😞', image: '/aac/emotion/dislike.png' },
  { id: 'emotion-hungry',        label: '배고파', categoryId: 'emotion', emoji: '😋', image: '/aac/emotion/hungry.png' },
  { id: 'emotion-tired',         label: '피곤해', categoryId: 'emotion', emoji: '😴', image: '/aac/emotion/tired.png' },
  { id: 'emotion-hurt',          label: '아파',   categoryId: 'emotion', emoji: '🤕', image: '/aac/emotion/hurt.png' },
  { id: 'emotion-scared',        label: '무서워', categoryId: 'emotion', emoji: '😨', image: '/aac/emotion/scared.png' },
  { id: 'emotion-bored',         label: '심심해', categoryId: 'emotion', emoji: '😑', image: '/aac/emotion/bored.png' },
  { id: 'emotion-excited',       label: '신나',   categoryId: 'emotion', emoji: '🥳', image: '/aac/emotion/excited.png' },
  { id: 'emotion-angry',         label: '화나',   categoryId: 'emotion', emoji: '😡', image: '/aac/emotion/angry.png' },
  { id: 'emotion-cool',          label: '시원해', categoryId: 'emotion', emoji: '❄️', image: '/aac/emotion/cool.png' },
  { id: 'emotion-full',          label: '배불러', categoryId: 'emotion', emoji: '😄', image: '/aac/emotion/full.jpg' },
  { id: 'emotion-sad',           label: '슬퍼',   categoryId: 'emotion', emoji: '😢', image: '/aac/emotion/sad.png' },
  { id: 'emotion-wait',          label: '잠깐만', categoryId: 'emotion', emoji: '✋', image: '/aac/emotion/wait.png' },
  { id: 'emotion-thanks',        label: '감사해', categoryId: 'emotion', emoji: '🙏', image: '/aac/emotion/thanks.png' },
  { id: 'emotion-uncomfortable', label: '불편해', categoryId: 'emotion', emoji: '😣', image: '/aac/emotion/uncomfortable.png' },
  { id: 'emotion-yes',           label: '맞아',   categoryId: 'emotion', emoji: '✅', image: '/aac/emotion/yes.png' },
  { id: 'emotion-sorry',         label: '미안해', categoryId: 'emotion', emoji: '😔', image: '/aac/emotion/sorry.png' },
  { id: 'emotion-no',            label: '아니',   categoryId: 'emotion', emoji: '❌', image: '/aac/emotion/no.png' },
  { id: 'emotion-frustrated',    label: '답답해', categoryId: 'emotion', emoji: '😤', image: '/aac/emotion/frustrated.png' },

  // 행동
  { id: 'action-eat',      label: '먹고싶어',  categoryId: 'action', emoji: '🍽️' },
  { id: 'action-drink',    label: '마시고싶어', categoryId: 'action', emoji: '🥤' },
  { id: 'action-sleep',    label: '자고싶어',  categoryId: 'action', emoji: '😴', image: '/aac/emotion/sleep.png' },
  { id: 'action-play',     label: '놀고싶어',  categoryId: 'action', emoji: '🎮', image: '/aac/action/play.png' },
  { id: 'action-go',       label: '가고싶어',  categoryId: 'action', emoji: '🚶' },
  { id: 'action-stop',     label: '그만해',    categoryId: 'action', emoji: '✋' },
  { id: 'action-help',     label: '도와줘',    categoryId: 'action', emoji: '🙏' },
  { id: 'action-watch',    label: '보고싶어',  categoryId: 'action', emoji: '👀', image: '/aac/emotion/miss.jpg' },
  { id: 'action-hello',    label: '안녕',      categoryId: 'action', emoji: '👋', image: '/aac/action/hello.png' },
  { id: 'action-sit',      label: '앉아',      categoryId: 'action', emoji: '🪑', image: '/aac/action/sit.png' },
  { id: 'action-standup',  label: '일어나',    categoryId: 'action', emoji: '⬆️', image: '/aac/action/standup.png' },
  { id: 'action-wash',     label: '씻어',      categoryId: 'action', emoji: '🚿', image: '/aac/action/wash.png' },
  { id: 'action-dress',    label: '옷입어',    categoryId: 'action', emoji: '👕', image: '/aac/action/dress.png' },
  { id: 'action-undress',  label: '옷벗어',    categoryId: 'action', emoji: '👕', image: '/aac/action/undress.png' },
  { id: 'action-undressme',label: '벗겨줘',    categoryId: 'action', emoji: '🙋', image: '/aac/action/undressme.png' },
  { id: 'action-turnon',   label: '켜줘',      categoryId: 'action', emoji: '💡', image: '/aac/action/turnon.png' },
  { id: 'action-turnoff',  label: '꺼줘',      categoryId: 'action', emoji: '🔌', image: '/aac/action/turnoff.png' },
  { id: 'action-open',     label: '열어줘',    categoryId: 'action', emoji: '🚪', image: '/aac/action/open.png' },
  { id: 'action-close',    label: '닫아줘',    categoryId: 'action', emoji: '🚪', image: '/aac/action/close.png' },
  { id: 'action-nosepick', label: '코파줘',    categoryId: 'action', emoji: '👃', image: '/aac/action/nosepick.png' },
  { id: 'action-music',    label: '음악들어',  categoryId: 'action', emoji: '🎵', image: '/aac/action/music.png' },
  { id: 'action-whattime', label: '몇시야',    categoryId: 'action', emoji: '⏰', image: '/aac/action/whattime.png' },
  { id: 'action-haircut',  label: '머리잘라줘', categoryId: 'action', emoji: '✂️', image: '/aac/action/haircut.png' },
  { id: 'action-dance',    label: '춤춰',      categoryId: 'action', emoji: '💃', image: '/aac/action/dance.png' },
  { id: 'action-clean',    label: '청소해',    categoryId: 'action', emoji: '🧹', image: '/aac/action/clean.png' },

  // 장소
  { id: 'place-home',       label: '집',    categoryId: 'place', emoji: '🏠', image: '/aac/place/home.png' },
  { id: 'place-school',     label: '학교',  categoryId: 'place', emoji: '🏫', image: '/aac/place/school.png' },
  { id: 'place-hospital',   label: '병원',  categoryId: 'place', emoji: '🏥', image: '/aac/place/hospital.png' },
  { id: 'place-park',       label: '공원',  categoryId: 'place', emoji: '🌳', image: '/aac/place/park.png' },
  { id: 'place-store',      label: '가게',  categoryId: 'place', emoji: '🏪', image: '/aac/place/restaurant.png' },
  { id: 'place-toilet',     label: '화장실', categoryId: 'place', emoji: '🚻', image: '/aac/place/bathroom.png' },
  { id: 'place-room',       label: '방',    categoryId: 'place', emoji: '🛏️' },
  { id: 'place-outside',    label: '밖',    categoryId: 'place', emoji: '🌤️' },
  { id: 'place-train',      label: '기차',  categoryId: 'place', emoji: '🚂', image: '/aac/place/train.png' },
  { id: 'place-playground', label: '놀이터', categoryId: 'place', emoji: '🛝', image: '/aac/place/playground.png' },
  { id: 'place-classroom',  label: '교실',  categoryId: 'place', emoji: '🏫', image: '/aac/place/classroom.png' },
  { id: 'place-car',        label: '자동차', categoryId: 'place', emoji: '🚗', image: '/aac/place/car.png' },

  // 사람
  { id: 'person-mom',     label: '엄마',   categoryId: 'person', emoji: '👩',   image: '/aac/people/mom.png' },
  { id: 'person-dad',     label: '아빠',   categoryId: 'person', emoji: '👨',   image: '/aac/people/dad.png' },
  { id: 'person-teacher', label: '선생님', categoryId: 'person', emoji: '👩‍🏫', image: '/aac/people/teacher.png' },
  { id: 'person-friend',  label: '친구',   categoryId: 'person', emoji: '👫',   image: '/aac/people/friend.png' },
  { id: 'person-you',     label: '너',     categoryId: 'person', emoji: '👉',   image: '/aac/people/you.png' },
  { id: 'person-me',      label: '나',     categoryId: 'person', emoji: '🙋' },
  { id: 'person-sibling', label: '형/언니', categoryId: 'person', emoji: '👧' },
  { id: 'person-grandma', label: '할머니', categoryId: 'person', emoji: '👵' },

  // 시간
  { id: 'time-now',       label: '지금',   categoryId: 'time', emoji: '⏰' },
  { id: 'time-today',     label: '오늘',   categoryId: 'time', emoji: '📅', image: '/aac/etc/today.png' },
  { id: 'time-morning',   label: '아침',   categoryId: 'time', emoji: '🌅' },
  { id: 'time-afternoon', label: '오후',   categoryId: 'time', emoji: '☀️' },
  { id: 'time-night',     label: '밤',     categoryId: 'time', emoji: '🌙' },
  { id: 'time-later',     label: '나중에', categoryId: 'time', emoji: '⏳' },
  { id: 'time-always',    label: '항상',   categoryId: 'time', emoji: '♾️' },
  { id: 'time-tomorrow',  label: '내일',   categoryId: 'time', emoji: '📆' },

  // 몸
  { id: 'body-head',      label: '머리', categoryId: 'body', emoji: '🤯', image: '/aac/body/head.png' },
  { id: 'body-stomach',   label: '배',   categoryId: 'body', emoji: '🫃', image: '/aac/body/stomach.png' },
  { id: 'body-hand',      label: '손',   categoryId: 'body', emoji: '✋' },
  { id: 'body-foot',      label: '발',   categoryId: 'body', emoji: '🦶' },
  { id: 'body-eye',       label: '눈',   categoryId: 'body', emoji: '👁️', image: '/aac/body/eye.png' },
  { id: 'body-ear',       label: '귀',   categoryId: 'body', emoji: '👂' },
  { id: 'body-mouth',     label: '입',   categoryId: 'body', emoji: '👄' },
  { id: 'body-nose',      label: '코',   categoryId: 'body', emoji: '👃', image: '/aac/body/nose.png' },
  { id: 'body-eyecrust',  label: '눈곱', categoryId: 'body', emoji: '👁️', image: '/aac/body/eyecrust.png' },
  { id: 'body-diarrhea',  label: '설사', categoryId: 'body', emoji: '🚽', image: '/aac/body/diarrhea.png' },
  { id: 'body-poop',      label: '똥',   categoryId: 'body', emoji: '💩', image: '/aac/body/poop.png' },

  // 물건
  { id: 'object-phone',    label: '핸드폰', categoryId: 'object', emoji: '📱', image: '/aac/etc/smartphone.png' },
  { id: 'object-book',     label: '책',     categoryId: 'object', emoji: '📚', image: '/aac/etc/book.png' },
  { id: 'object-pen',      label: '연필',   categoryId: 'object', emoji: '✏️' },
  { id: 'object-bag',      label: '가방',   categoryId: 'object', emoji: '🎒' },
  { id: 'object-tv',       label: 'TV',     categoryId: 'object', emoji: '📺', image: '/aac/etc/tv.png' },
  { id: 'object-toy',      label: '장난감', categoryId: 'object', emoji: '🧸', image: '/aac/etc/toy.png' },
  { id: 'object-clothes',  label: '옷',     categoryId: 'object', emoji: '👕' },
  { id: 'object-medicine', label: '약',     categoryId: 'object', emoji: '💊', image: '/aac/action/medicine.png' },
  { id: 'object-song',     label: '노래',   categoryId: 'object', emoji: '🎵', image: '/aac/etc/song.png' },
  { id: 'object-movie',    label: '영화',   categoryId: 'object', emoji: '🎬', image: '/aac/etc/movie.jpg' },
  { id: 'object-study',    label: '공부',   categoryId: 'object', emoji: '📖', image: '/aac/etc/study.png' },
  { id: 'object-computer', label: '컴퓨터', categoryId: 'object', emoji: '💻', image: '/aac/etc/computer.png' },

  // 숫자
  { id: 'number-0', label: '0', categoryId: 'number', emoji: '0️⃣', image: '/aac/number/0.png' },
  { id: 'number-1', label: '1', categoryId: 'number', emoji: '1️⃣', image: '/aac/number/1.png' },
  { id: 'number-2', label: '2', categoryId: 'number', emoji: '2️⃣', image: '/aac/number/2.png' },
  { id: 'number-3', label: '3', categoryId: 'number', emoji: '3️⃣', image: '/aac/number/3.png' },
  { id: 'number-4', label: '4', categoryId: 'number', emoji: '4️⃣', image: '/aac/number/4.png' },
  { id: 'number-5', label: '5', categoryId: 'number', emoji: '5️⃣', image: '/aac/number/5.png' },
  { id: 'number-6', label: '6', categoryId: 'number', emoji: '6️⃣', image: '/aac/number/6.png' },
  { id: 'number-7', label: '7', categoryId: 'number', emoji: '7️⃣', image: '/aac/number/7.png' },
  { id: 'number-8', label: '8', categoryId: 'number', emoji: '8️⃣', image: '/aac/number/8.png' },
  { id: 'number-9', label: '9', categoryId: 'number', emoji: '9️⃣', image: '/aac/number/9.png' },
];

export function getWordsByCategory(categoryId: string): Word[] {
  return words.filter((w) => w.categoryId === categoryId);
}
